### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by isaacseymour** [gocardless/ibandit#10]
- [x] Overload `IBAN.new` to receive local details or IBAN #9 
- [x] Rename `IBANBuilder` to `IBANAssembler`, and return string instead of `IBAN` instance #12
- [x] Pull input cleaning out of `IBANAssembler` #13 and #14 
- [x] Pull IBAN string splitting into `IBANSplitter` #11 
- [x] Improve cleaning #15
